repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: "ruff auto-fix"
        entry: uv run --group dev ruff check
        language: system
        types: [python]
        args:
          - "--fix"
          - "--force-exclude"  # respect pyproject.toml's exclude settings even when passing in explicit file list
      - id: ruff-format
        name: "ruff format"
        entry: uv run --group dev ruff format
        language: system
        types: [python]
        args:
          - "--force-exclude"  # respect pyproject.toml's exclude settings even when passing in explicit file list
      - id: mypy
        name: mypy
        entry: uv run --group dev mypy
        language: system
        pass_filenames: false
        types: [python]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
